### ISSUE TITLE
Better Methods for Fuzzy Joins?

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#11]
The code for this issue can be found in the scan_tidying_functions.R file, in the center_scan() function, line 123. 

I've been testing out the "fuzzyjoin" package and the difference_left_join() function as a way to join the trace and time_dots csv files to center the scan. However, this process creates excess rows of the same data point since some points along the trace are close to both time dots (i.e., the point (1.5, 1.3) could have 2 duplicated rows since this point was close to two different time dots-- this still happened even after I tried different max_dist values since the distance between time dots changes). I removed these excess rows using the duplicated() function on unique x and y combinations, which logically shouldn't remove any observations. However, I noticed that this process dropped quite a few observations (~40,000) from the original trace file.

After some investigating, I think this is because the original file also contained duplicated values after image processing. When I run trace[!duplicated(trace[,1:2]),] on the trace file after tidying, I get the same number of observations as the trace after it had been centered. 

Ultimately, I am hesitant to drop duplicated values from the trace, since 40,000 observations seems like quite a chunk of observations to me. Could there be a better method for a fuzzy merge?

**Comment by dschwilk** [comment]
I can take a look, but shouldn't there be only one of each x (time) value for a fully cleaned trace? A seal can only be at one depth at any time. And if the y values are also the same than that is truly duplicated information and why wouldn't you toss it?  But I'd want to understand how those originate first. This is a line thickness issue in the scan, correct?  I assume you want to leave those in for now because they might influence the smoothing fit later?   I'll assign this to myself and see what I can figure out.

**Comment by EmmaLiTsai** [comment]
I think this issue might stem from the wand selection tool in ImageJ. During image processing, I select each segment of the trace using the wand tool and then list the coordinates of my whole selection (after the scale and origin have been set). This process seems to produce some unnecessary duplicated points in the trace csv file. I also investigated the points that were duplicated in the file and they didn't exhibit any concerning pattern, and removing them didn't seem to influence the dive patterns contained in the overall record. From this, I believe it would reasonably be okay to remove them when I tidy the traces...

**Comment by dschwilk** [comment]
OK, I'm fine with that. Go ahead and remove them in an early step and refer to this issue and close the issue.
