### ISSUE TITLE
Depth Calibration Approach

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#12]
I've been trying different approaches for the depth calibration. For context, here is what the psi calibration curve looks like at the end of the scan: 

![image](https://user-images.githubusercontent.com/71040203/113521494-62fb4c00-955f-11eb-9af0-806967670c44.png)

At the moment, the user must manually enter the breaks and labels for the cut() function in the transform_psitodepth function in the dive_traces_tidy.R file, line 168. The breaks would be the y_vals of the psi calibration curve at the end of the scans, and the labels would be the psi value (i.e., break = -5 to 1.43, label = 100:1.43 for the 100psi curve, and so on). I combined 100:1.43 in the labels of these breaks so I could do a simple separate() function to use these numerical values in depth calculations. 

However, this seems a bit inefficient to me. Would there a way to get these break values automatically? I'm thinking this would involve some derivatives, but was having difficulty thinking of an elegant approach that wouldn't accidentally pick up a deep dive the seal made.

**Comment by dschwilk** [comment]
If I'm understanding this correctly, I don't think making it fully automatic is feasible. I assume that those hand written numbers are the data? Someone already wrote those, correct. So the trace has a bunch of sharpie looking writing at the end as well as the numbers written with a finer pencil/pen? I guess I don't understand your comment about derivatives.  Can you explain this calibration in more detail? I do think the data should be in a data file, not the code, however. I suggest a separate file associated with each scan that has the calibration data.

**Comment by EmmaLiTsai** [comment]
Yes! At the end of the trace there is the psi curve from when the past researchers put the TDR in a pressure chamber. The small pencil markings are measurements from the 90's that indicate the distance (in inches) of that pressure marking from the top border of the trace. I haven't been using these measurements since I'm essentially doing the same calculations but from y = 0 and in centimeters (I have some sample calculations to confirm this). 

For the pressure calibration, I am currently breaking the trace up into different pressure categories using the cut() function (i.e., a point with the y_val = 1.20cm would fall into the 100psi category since it is less than the defined 100psi y_value of 1.43cm). With these pressure categories, I could then do some small proportions to determine the pressure of a specific point and therefore the depth. I definitely think that breaking out the pressure calibration values into a separate file would be much simpler-- I'll give that a go!

**Comment by EmmaLiTsai** [comment]
Tried out this new method in the dive_traces_tidy.R file (pushed to the tsai branch) and the code looks cleaner. I think this is the method I will move forward with for the traces with a psi calibration curve at the end.

**Comment by dschwilk** [comment]
Is this code done? Can this be closed?

**Comment by EmmaLiTsai** [comment]
Yes, issue is resolved.
