### ISSUE TITLE
Height of Transducer Arm Pivot Point (Center_Y)

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#13]
Center_Y is the height of the transducer arm pivot point from depth = 0, and this value is used as a constant for the arc removal equation. I initially thought this value was constant across all traces, but after testing arc removal on some of the records from the 1970's I noticed that there is slight variation in this value (+/- about ~1 cm from my original measurement) which caused some of the traces to look slightly skewed after arc removal. This variation between records likely exists because of small changes in the position of depth = 0 (i.e., transducer arm pivot point might be closer to depth = 0 on one record, but farther in another record). 

I've been working on a mathematical approach to determine the height of the transducer arm pivot point using two points along a single dive in the record. My current math (by hand) is basically solving a system of equations with circles using the two points along a single dive, but this creates messy code and assumes that the two points happened at the same time. Is there a better solution that I may be overlooking? 

Possible math to solve this problem has been added to the "tsai" branch in r_scripts/find_center_y.R file. This is still a work in progress, but shows my most updated thought process.

**Comment by dschwilk** [comment]
Can you better explain the cause?  I don't quite understand. Did the device hardware change or is this something about film alignment?

**Comment by EmmaLiTsai** [comment]
Yes! I believe there is likely very small variation in hardware between KBTDRs. From the calculations that I've done so far, I found the variation of this height to be <1mm when scaled down to the size of the original film (3.2cm). So, any slight difference in hardware would scale up to a much larger issue after the records were magnified 7x. 

At the moment, the math that I have uses two points (start of the dive and deepest part of the dive) along a V-shaped dive to estimate the height of the transducer arm pivot point. It first transforms the deepest part of the dive over in the -x direction (using the depth and assuming the seal is swimming at a constant rate) such that the two points would lie on the same circle. I then used some geometry to calculate the height of this circle, which would give me an estimate of the center_y value.

**Comment by EmmaLiTsai** [comment]
Sample calculations made in the r_scripts/find_center_y.R provide an estimate of the height of this arm, but this value needs to be visually confirmed to make sure it does not introduce any abnormal skew across the record after arc removal.
