### ISSUE TITLE
Removing Dependencies 

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#25]
At the moment, we have dependencies on six packages: 

- _dplyr_: select(), mutate(), case_when(), group_by(), summarize(), filter(), for basic data wrangling.
- _tidyr_: separate(), drop_na(), for tidying strings and redundant points.
- _lubridate_: ymd_hms() for POSIXct date times. 
- _caTools_: runmean() and runquantine() for zero-offset correction and dive detection. 
- _zoo_: na.approx() for interpolating depth points for sparse records. 
- _diveMove_: readTDR(), calibrateDepth(), diveStats(), to find the best spar value for spline smoothing by determining how different values influence the dive statistics from the record. This dependency wasn't ideal, but I believe this method is much better over conventional cross validation and AIC methods. 

What is the general workflow for removing dependencies? Do other people usually export the code for these functions from other packages? Just wanted to open this up as an issue to touch base before continuing with code!

**Comment by dschwilk** [comment]
We don't necessarily need to remove them.  That looks quite reasonable. The main bit of work is that we might need to use standard-evaluation versions of the tidyverse functions. For everything else, you just need to remove all `library()` calls and explicitly call functions using the `package::function` notation. Then in the package metadata we record the dependencies so that they are automatically installed when someone installs your package.

You have been doing great on this! I need to devote some time soon to help get it ready as a package.

>  Do other people usually export the code for these functions from other packages?

No, with rare exceptions. Generally best to rely on the package.

**Comment by EmmaLiTsai** [comment]
Sounds great! All of the package functions should be tagged with the` package::function` notation, but I'll double-check to make sure. I'll also read up on package development and the document you linked in Issue #4 to see if I can start drafting up the standard-evaluation versions of the tidyverse functions. It's great to see this coming together!

**Comment by dschwilk** [comment]
Do you want me to start turning it into a package or do you want to try it? Are you going to use the `usethis` package to set it up (https://b-rodrigues.github.io/modern_R/package-development.html) ? I think explicit use of `.data` inside tidyverse function calls will take care of most of the nonstandard (data masking) stuff in dplyr, etc.

**Comment by EmmaLiTsai** [comment]
I'll go ahead and try turning it into a package and will open up issues as I encounter them-- it'll be good practice for future projects! I plan to use the `usethis` package and am reading through the documentation now. Thank you for the helpful link. 

After reading a bunch of articles yesterday on standard evaluation, I also agree that the `.data[[value]]` notation should be able to handle the nonstandard evaluation in the tidyverse functions. I'll try that out soon!

**Comment by EmmaLiTsai** [comment]
All NSE should be converted to SE
