### ISSUE TITLE
Package Check Warning - qpdf

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#27]
I've been building the package in /recoverKBTDR and have a couple of quick questions before moving forward (see /recoverKBTDR/package_dev_code.R for an overview of the development workflow I've been using). After adding proper documentation for the functions and data in the package, I've narrowed the package check down to just one warning and one note: 

- warning: 'qpdf' is needed for checks on size reduction of PDFs. 
- note: visible binding errors from some of the functions that add data frames to the global environment. 

Is the qpdf warning something that we need to worry about? I've done a few google searches on this warning, but am unsure if this is something that needs fixing before package release. 

Also, do you have any tips for adding graphs to a vignette? I'd like to use graphs (preferably from ggplot... but this might add an extra dependency) to illustrate the different recovery steps, but kept getting knitting errors during package check.

**Comment by dschwilk** [comment]
That is good! I'll take a look. We can install qpdf and see if that solves that error. I assume that has to do with pdfs in the vignette?

I'll look into the other one about visible binding errors.  Do you have functions that store data in the global environment? I guess I can take a look.

**Comment by EmmaLiTsai** [comment]
Yes! I have three functions that add data frames to the global environment: 

- R/read_trace.R: read_trace() function that just illustrates the tidying process using raw csv files from ImageJ, mainly just used as an example
- R/centering_functions.R: center_scan() adds the centered psi calibration curve (if available) from the end of the record to the global environment 
- R/helper_functions.R: find_best_spar() adds the dive statistics for a record to the global environment, intended to help the user find the best spar value to use for spline smoothing

These functions might've made more sense when I was working with my own data, but I'm unsure how common it is for packages to add data frames to the global environment. I also get a note about using .data within dplyr functions, which might be something I did incorrectly when translating code to standard evaluation. I'll do some research to figure this out!

**Comment by dschwilk** [comment]
Ok, we'll want to change those. The functions can accept and return data frames instead. In general, global variables are a bad idea. Instead, one might use within package variables for things like setting options, or keeping track of some package state. But I think your package should not need anything like that?

**Comment by EmmaLiTsai** [comment]
I don't think this package should need anything like that, so I'll go ahead and work on editing these functions. My original idea behind adding things to the global environment was that one function could basically "return" multiple things without the user having to wrestle with a list or running multiple functions, but I can see how that would be bad practice in a package. I'll go ahead and assign this one to myself.

**Comment by dschwilk** [comment]
I think most functions should take and return data frames so it 
should
not be too bad. But I need to look at the code again.

-DWS


On Fri 10 Sep 2021 at 10:37, EmmaLi Tsai 
***@***.***> wrote:

> I don't think this package should need anything like that, so 
> I'll go ahead and work on
> editing these functions. My original idea behind adding things 
> to the global environment
> was that one function could basically "return" multiple things 
> without the user having to
> wrestle with a list or running multiple functions, but I can see 
> how that would be bad
> practice in a package. I'll go ahead and assign this one to 
> myself.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or 
> Android. 


-- 
Dylan W. Schwilk
Associate Professor
Department of Biological Sciences
Texas Tech University
Lubbock, TX 79409-3131

Phone - (806) 834-0902
Web - http://www.schwilk.org

**Comment by EmmaLiTsai** [comment]
I fixed the .data global binding issue by adding: `@importFrom rlang` to the functions that use dplyr, and also reorganized a few of the functions so they no longer add things to the global environment. However, I left a few functions where I think it makes sense (i.e., the read_trace() function that takes raw trace and time dots ImageJ csv files and makes them tidy), so this note still pops up. Do you think I should change this function to return a list instead? 

I still get the qpdf warning during package check, so I'll also check this out!

**Comment by dschwilk** [comment]
I think that the code should avoid any global objects. But I can help figure out the organization. remember, your package has API level functions and internal functions and there is a naming convention for these. You only expose a few functions to the user and these should have a consistent interface and should not have side effects.  But I'm speaking generally and need to look at the code again to help more.  You might need to bug me.

**Comment by EmmaLiTsai** [comment]
I was able to reorganize the workflow have successfully removed the global binding errors during package check. I still get the warning: "'qpdf' is needed for checks on size reduction of PDFs", but it seems to be a very common warning that's often ignored by other package developers. The vignette I wrote is also rather short, so I don't have any reason to believe it would be a large PDF... 

I've been working on my second chapter lately, but I plan to devote more time to this soon. I'm mainly hoping to tidy up the structure and package documentation, but it's coming together!

**Comment by dschwilk** [comment]
Sounds good.

To avoid that warning you would need to install qpdf. No big deal 
wither way. It runs locally during the check. 

I was out of town last week and am catching up./ Let me know when 
you need me to do something.

-Dylan

On Tue 02 Nov 2021 at 15:48, EmmaLi Tsai 
***@***.***> wrote:

> I was able to reorganize the workflow have successfully removed 
> the
> global binding errors during package check. I still get the 
> warning:
> "'qpdf' is needed for checks on size reduction of PDFs", but it 
> seems
> to be a very common warning that's often ignored by other 
> package
> developers. The vignette I wrote is also rather short, so I 
> don't
> have any reason to believe it would be a large PDF...
>
> I've been working on my second chapter lately, but I plan to 
> devote
> more time to this soon. I'm mainly hoping to tidy up the 
> structure
> and package documentation, but it's coming together!
>
> -
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or 
> Android.
> *


-- 
Dylan W. Schwilk
Associate Professor
Department of Biological Sciences
Texas Tech University
Lubbock, TX 79409-3131

Phone - (806) 834-0902
Web - http://www.schwilk.org
